//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttlsale
    {
        public string month { get; set; }
        public Nullable<int> rice { get; set; }
        public Nullable<int> wheats { get; set; }
        public Nullable<int> sugar { get; set; }
        public Nullable<int> atta { get; set; }
        public Nullable<int> kerozine { get; set; }
        public int no { get; set; }
    }
}
